/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: a8281f18a1876616692797315cabbccb)
interface __BaseEnv_CloudflareEnv {
	NEXT_INC_CACHE_KV: KVNamespace;
	ASSETS: Fetcher;
	EADWYN_DATA_SOURCE: "auto";
	NEXT_CACHE_DO_QUEUE: DurableObjectNamespace<import("./.open-next/worker").DOQueueHandler>;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
	COORDINATOR: Fetcher /* eadwyn-coordinator */;
	GOVERNANCE: Fetcher /* eadwyn-governance */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
		durableNamespaces: "DOQueueHandler";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EADWYN_DATA_SOURCE">> {}
}
