/**
 * LocalNode — the mock training node client.
 *
 * Lifecycle: registerNode() → prepareLocalUpdate() → submitUpdate().
 * The node keeps its private key; the coordinator keeps its public key; the
 * aggregator verifies every update against it. Data never leaves the node:
 * only the signed update and its delta (uploaded to object storage) travel.
 */
import { createFederationClient, type FederationClient } from "@eadwyn/federation-sdk";
import {
  type DeltaUploadTarget,
  type HeartbeatResponse,
  type NodeCapabilities,
  type NodeIdentity,
  type NodeRole,
  type RegisterNodeResponse,
  type SubmitUpdateResponse,
  type TrainingRound,
  type TrainingUpdate,
  TrainingUpdateSchema,
  type UnsignedTrainingUpdate,
} from "@eadwyn/shared-protocol";
import {
  generateNodeKeyPair,
  type NodeKeyPair,
  signTrainingUpdate,
} from "@eadwyn/shared-protocol/signing";
import { simulateLocalTraining } from "./mock-training";

export interface LocalNodeConfig {
  displayName: string;
  role?: NodeRole;
  podId?: string;
  region?: string;
  capabilities?: NodeCapabilities;
  coordinatorUrl: string;
  aggregatorUrl: string;
  /** Persisted node keys. A fresh pair is generated on first registration when omitted. */
  keyPair?: NodeKeyPair;
  /** Seed for deterministic mock training. */
  seed?: number;
  fetch?: typeof fetch;
  timeoutMs?: number;
  now?: () => Date;
}

export interface PrepareUpdateInput {
  samples: number;
  steps?: number;
  knowledgeItemIds?: string[];
}

export interface PreparedUpdate {
  update: TrainingUpdate;
  /** The delta bytes (safetensors). Uploaded by submitUpdate unless storage is unavailable. */
  delta: Uint8Array;
  upload: DeltaUploadTarget;
}

export interface LocalNode {
  /** Available after registerNode(). */
  readonly keyPair: NodeKeyPair;
  readonly identity: NodeIdentity | undefined;
  readonly activeRound: TrainingRound | undefined;
  readonly client: FederationClient;
  registerNode(): Promise<RegisterNodeResponse>;
  heartbeat(): Promise<HeartbeatResponse>;
  prepareLocalUpdate(input: PrepareUpdateInput): Promise<PreparedUpdate>;
  submitUpdate(prepared: PreparedUpdate): Promise<SubmitUpdateResponse>;
}

export function createLocalNode(config: LocalNodeConfig): LocalNode {
  let keyPair = config.keyPair;
  const now = config.now ?? (() => new Date());
  const client = createFederationClient({
    coordinatorUrl: config.coordinatorUrl,
    aggregatorUrl: config.aggregatorUrl,
    fetch: config.fetch,
    timeoutMs: config.timeoutMs,
  });

  let identity: NodeIdentity | undefined;
  let activeRound: TrainingRound | undefined;
  let updatesPrepared = 0;

  const requireRegistered = (): {
    identity: NodeIdentity;
    activeRound: TrainingRound;
    keys: NodeKeyPair;
  } => {
    if (!identity || !activeRound || !keyPair) {
      throw new Error("node is not registered; call registerNode() first");
    }
    return { identity, activeRound, keys: keyPair };
  };

  return {
    client,
    get keyPair() {
      if (!keyPair) throw new Error("node keys are generated by registerNode()");
      return keyPair;
    },
    get identity() {
      return identity;
    },
    get activeRound() {
      return activeRound;
    },

    async registerNode() {
      keyPair ??= await generateNodeKeyPair();
      const response = await client.coordinator.registerNode({
        displayName: config.displayName,
        role: config.role ?? "device",
        podId: config.podId,
        region: config.region,
        publicKey: keyPair.publicKey,
        capabilities: config.capabilities ?? { compute: "cpu" },
      });
      identity = response.node;
      activeRound = response.activeRound;
      return response;
    },

    async heartbeat() {
      const { identity: me } = requireRegistered();
      const response = await client.coordinator.heartbeat(me.nodeId);
      identity = response.node;
      activeRound = response.activeRound;
      return response;
    },

    async prepareLocalUpdate(input) {
      const { identity: me, activeRound: round, keys } = requireRegistered();
      const steps = input.steps ?? Math.max(10, Math.round(input.samples / 8));
      updatesPrepared += 1;
      const trained = await simulateLocalTraining({
        seed: (config.seed ?? 1) * 1_000 + updatesPrepared,
        samples: input.samples,
        steps,
      });
      const updateId = crypto.randomUUID();
      // Ask where the delta will live before signing: its URI is part of what we sign.
      const upload = await client.aggregator.requestUploadTarget({
        updateId,
        roundId: round.roundId,
        nodeId: me.nodeId,
        sha256: trained.sha256,
        bytes: trained.delta.byteLength,
      });
      const unsigned: UnsignedTrainingUpdate = {
        updateId,
        nodeId: me.nodeId,
        roundId: round.roundId,
        baseModelVersion: round.baseModelVersion,
        delta: { uri: upload.uri, sha256: trained.sha256, bytes: trained.delta.byteLength },
        metrics: trained.metrics,
        knowledgeItemIds: input.knowledgeItemIds ?? [],
        createdAt: now().toISOString(),
      };
      const update = TrainingUpdateSchema.parse({
        ...unsigned,
        signature: await signTrainingUpdate(unsigned, keys.privateKey),
      });
      return { update, delta: trained.delta, upload };
    },

    async submitUpdate(prepared) {
      requireRegistered();
      await client.aggregator.uploadDelta(prepared.upload, prepared.delta);
      return client.aggregator.submitUpdate(prepared.update);
    },
  };
}
